### PR TITLE
Fix invalid images generation for some slugs with leading slash

### LINKED ISSUE #61: Possible incompatibility with Astro 4.10.2 - Invalid images
Hello there!
Thanks a lot for this package 🙏 

### Description

From my initial analysis, it seems there may be an issue when using Astro OG Canvas with Astro version 4.10.2 and above.

Based on my understanding, Astro OG Canvas should be compatible since its peer dependency is specified as `"astro": "^3.0.0 || ^4.0.0"`.

However, images built from Astro version 4.10.2 onwards appear to be invalid in my environment:
- They cannot be opened with a regular image preview tool.
- Their size is significantly smaller (e.g., from 61K to 14K); probably due to the fact they are invalid.

Screenshot 2024-07-01 at 23 21 44

### Reproducible environment

To reproduce the issue with my current environment, please follow these steps:

```bash
cd /tmp
git clone git@github.com:Open-reSource/openresource.dev.git
cd openresource.dev
npm i
npm run build

# Open for instance .vercel/output/static/open-graph/articles/can-i-take-this-issue.png 
# It's going to be invalid
```

This build uses Astro 4.11.3.

### Digging into the Past

The error starts to occur from this commit: https://github.com/Open-reSource/openresource.dev/commit/b96782ad65aba543738aed5fc4b3d7a9d9fea8b9

Notably, the code related to Astro OG Canvas hasn't changed for a long time and can be found here: https://github.com/Open-reSource/openresource.dev/blob/main/src/pages/open-graph/%5B...path%5D.ts. It worked previously and appears correct according to the documentation.

Using the reproducible environment, you can verify the issue:

```bash
git checkout b96782ad65aba543738aed5fc4b3d7a9d9fea8b9
# You can force in "package.json" the version of Astro to be strictly 4.10.2 just to be sure
npm i
npm run build
```

The issue persists, as expected.

Now, if you change `"astro": "^4.10.2"` to `"astro": "4.10.1"` in the `package.json` and then run `npm i; npm run build`, you'll find that the image at `.vercel/output/static/open-graph/articles/can-i-take-this-issue.png` is now valid.

This is what makes me think there's an incompatibility starting from Astro 4.10.2 precisely.

### Next steps?

It seems there's an incompatibility between Astro OG Canvas and Astro version 4.10.2 (and later versions).

My knowledge is limited in diagnosing the root cause further 😬 
I can try, but I'll maybe need some guidance to where to look at.
If you need additional actions or tests to gather more precise information on my side, please let me know, and I'll follow your guidance 🙏

### PR DESCRIPTION
**Pull request by julien-deramond**
### Description

Closes #61

Thanks a lot @delucis for helping me investigate the issue in https://github.com/delucis/astro-og-canvas/issues/61. It was a really interesting use case. It was a really interesting use case. I'm still not entirely sure if it could be a bug in Astro, but let's strengthen `astro-og-canvas` by modifying the comparison method in `getOGImage` to compare slugs both with and without leading paths.

I quickly experimented with different approaches within `astro-og-canvas` but the suggestion in https://github.com/delucis/astro-og-canvas/issues/61#issuecomment-2211116517 seems to be the most robust solution.

Since the patch is a simple one-line fix, feel free to close the PR if there's a better alternative.

The complexity of the problem stretched my creativity for the commit message and changeset wording
Feel free to adjust them as needed.

I haven't added any specific tests, but it probably can be possible if needed.

#### How to test with the original issue

One approach is to:
1. Get the Astro minimal example at https://github.com/withastro/astro/tree/main/examples/minimal that can be built by executing `pnpm --filter @example/minimal run build`
2. Create the files described in https://github.com/delucis/astro-og-canvas/issues/61#issuecomment-2203490945.
3. Compile `astro-og-canvas` with the patch
4. `npm run build ; rm /Users/xxx/as
tro/astro/examples/minimal/node_modules/astro-og-canvas/dist/* ; cp dist/* /Users/xxx/astro/astro/examples
/minimal/node_modules/astro-og-canvas/dist/` (there's probably a way to do it with `pnpm link` or `npm link` but I was too lazy this morning 😇)
5. Compile the Astro minimal example
6. Observe the generated images

_Note: I've also done the same thing for my repo at https://github.com/Open-reSource/openresource.dev and the images are well generated_

### CODE REVIEW

File: packages/astro-og-canvas/src/routing.ts [hunk 1]
```diff
@@ -24,7 +24,9 @@ function makeGetStaticPaths({
 function createOGImageEndpoint({ getSlug = pathToSlug, ...opts }: OGImageRouteConfig): APIRoute {
   return async function getOGImage({ params }) {
     const pageEntry = Object.entries(opts.pages).find(
-      (page) => getSlug(...page) === params[opts.param]
+      (page) => {
+        return getSlug(...page) === params[opts.param] || getSlug(...page).replace(/^\//g, "") === params[opts.param]
```
Comment (delucis) [inline packages/astro-og-canvas/src/routing.ts]: The default `getSlug()` is pretty cheap, but I guess we should probably still skip calling it twice:

```suggestion
        const slug = getSlug(...page);
        return slug === params[opts.param] || slug.replace(/^\//, "") === params[opts.param]
```

(Also don’t think we need the global `g` flag on the regular expression?)

File: .changeset/lucky-seahorses-relax.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro-og-canvas': patch
+---
+
+Fix invalid images generation for some slugs with leading slash
```
Comment (delucis) [inline .changeset/lucky-seahorses-relax.md]: Maybe worth mentioning the Astro version this was impacted in:

```suggestion
Fixes image generation for slugs with a leading slash in Astro ≥4.10.2
```

**Review by delucis — COMMENTED** [review]
Nice! Thank you @julien-deramond this is pretty much what I was thinking. Left a couple of tiny notes, but this is great!

**Review by delucis — COMMENTED** [review]
Nice! Thank you @julien-deramond this is pretty much what I was thinking. Left a couple of tiny notes, but this is great!

File: packages/astro-og-canvas/src/routing.ts (hunk 1 above)
Comment (julien-deramond) [reply packages/astro-og-canvas/src/routing.ts]: Definitely better with the `const` approach, we never know if `getSlug()` is less cheap in the future 👌 

> Also don’t think we need the global g flag on the regular expression?

It works without it, yeah, let's go like this.

Thanks for the feedback, they're all commited.

**Review by delucis — APPROVED** [review]
Thanks again for digging into the cause here and fixing it @julien-deramond!
