### PR TITLE
Fix unexpected slug truncation for paths without extension

### LINKED ISSUE #11: Incorrect route parsing, using the demo snippet
Hey!

I've stumbled upon this issue, using `v1.9.0`:

```ts
import { OGImageRoute } from 'astro-og-canvas';

export const { getStaticPaths, get } = OGImageRoute({
	param: 'route',
	// pages: await import.meta.glob('/src/pages/**/*.md', { eager: true }),

	pages: {
		Why: {
			title: 'Why Astro?',
			description:
				'Astro is an all-in-one web framework for building fast, content-focused websites. Learn more.',
		},
		who: {
			title: 'Why Astro?',
			description:
				'Astro is an all-in-one web framework for building fast, content-focused websites. Learn more.',
		},
	},
	getImageOptions: (_path, page) => ({
		title: page.title,
		description: page.description,
	}),
});

console.table(getStaticPaths());
```

yields:

```sh
06:48:14 [astro] reload /src/pages/og/[...route].ts
┌─────────┬─────────────────────┐
│ (index) │       params        │
├─────────┼─────────────────────┤
│    0    │ { route: 'Wh.png' } │
│    1    │ { route: 'wh.png' } │
└─────────┴─────────────────────┘
06:48:15 [getStaticPaths] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/og/who`.

Possible dynamic routes being matched: src/pages/og/[...route].ts, src/pages/[...page].astro.
06:48:15 [serve]    404                                  /og/who
```

I did get `generateOpenGraphImage` to work separately from the router util.

Thanks for your work 👏

### PR DESCRIPTION
**Pull request by AlexTMjugador**
Resolves #11 by implementing the change described at https://github.com/delucis/astro-og-canvas/issues/11#issuecomment-1472828325.

### CODE REVIEW

File: packages/astro-og-canvas/src/routing.ts [hunk 1]
```diff
@@ -4,8 +4,7 @@ import type { OGImageOptions } from './types';
 
 const pathToSlug = (path: string): string => {
   path = path.replace(/^\/src\/pages\//, '');
-  const extIndex = path.lastIndexOf('.');
-  path = path.slice(0, extIndex) + '.png';
+  path = path.replace(/\..*$/, '') + '.png';
```
Comment (delucis) [inline packages/astro-og-canvas/src/routing.ts]: Sorry to take a while to get to this, going to get this merged now!

Making one change here though:

```suggestion
  path = path.replace(/\.[^\.]*$/, '') + '.png';
```

This makes sure we don’t truncate too aggressively in cases where the path is something like `'thing.something.md'`. `replace(/\..*$/, '')` would give `'thing'`, instead of `'thing.something'`.

**Review by delucis — APPROVED** [review]
Thanks again for contributing @AlexTMjugador!

File: packages/astro-og-canvas/src/routing.ts (hunk 1 above)
Comment (AlexTMjugador) [reply packages/astro-og-canvas/src/routing.ts]: Good catch. Thanks for the heads-up!
